version: "3"

services:
  review:
    build: ./services/review
    volumes:
      - ./workdir:/workdir
  textlint:
    image: node:11.7.0-alpine
    working_dir: /workdir
    volumes:
      - .:/workdir
